In [1]:
import pandas as pd

In [2]:
from sklearn import preprocessing

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.metrics import accuracy_score

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
dataset = pd.read_csv("train.csv")

In [7]:
le = preprocessing.LabelEncoder()

In [8]:
le.fit(dataset["Sex"])

LabelEncoder()

In [9]:
print(le.classes_)

['female' 'male']


In [10]:
dataset["Sex"] = le.transform(dataset["Sex"])

In [11]:
le.fit(dataset["Embarked"])

LabelEncoder()

In [12]:
print(le.classes_)

['C' 'Q' 'S']


In [13]:
dataset["Embarked"] = le.transform(dataset["Embarked"])

In [14]:
from sklearn import neighbors

In [15]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
884          887         0       2   
885          888         1       1   
886          889         0       3   
887          890         1       1   
888          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1   
2                               Heikkinen, Miss. Laina    0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1   
4                             Allen, Mr. William Henry    1  35.0      0   
..                                                 ...  ...   ...    ...   
884                              Montvila, Rev. Juozas    1  27.0      0   
885                       Graham, Miss. Margaret Edith    0  19.0      0   
886           Johnston, Miss. Catherine Helen "Carrie"    0  45.0      1   
887                              Behr, Mr. Karl Howell    1  26.0      0   
888                                Dooley, Mr. Patrick    1  32.0      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN         2  
1        0          PC 17599  71.2833   C85         0  
2        0  STON/O2. 3101282   7.9250   NaN         2  
3        0            113803  53.1000  C123         2  
4        0            373450   8.0500   NaN         2  
..     ...               ...      ...   ...       ...  
884      0            211536  13.0000   NaN         2  
885      0            112053  30.0000   B42         2  
886      2        W./C. 6607  23.4500   NaN         2  
887      0            111369  30.0000  C148         0  
888      0            370376   7.7500   NaN         1  

[889 rows x 12 columns]

In [19]:
x1 = dataset.drop(["Name", "PassengerId", "Ticket", "Cabin"],axis=1)

In [20]:
x1

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
884         0       2    1  27.0      0      0  13.0000         2
885         1       1    0  19.0      0      0  30.0000         2
886         0       3    0  45.0      1      2  23.4500         2
887         1       1    1  26.0      0      0  30.0000         0
888         0       3    1  32.0      0      0   7.7500         1

[889 rows x 8 columns]

In [21]:
import numpy as np
x1["Age"] = x1["Age"].astype(int)
x1["Fare"] = x1["Fare"].astype(int)

In [22]:
x1

Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0           0       3    1   22      1      0     7         2
1           1       1    0   38      1      0    71         0
2           1       3    0   26      0      0     7         2
3           1       1    0   35      1      0    53         2
4           0       3    1   35      0      0     8         2
..        ...     ...  ...  ...    ...    ...   ...       ...
884         0       2    1   27      0      0    13         2
885         1       1    0   19      0      0    30         2
886         0       3    0   45      1      2    23         2
887         1       1    1   26      0      0    30         0
888         0       3    1   32      0      0     7         1

[889 rows x 8 columns]

# When KNN Value is 2

In [23]:
for a in x1.columns:
    y = x1[a]
    x2 = x1.drop([a],axis=1)
    
    x_train, x_test, y_train, y_test = train_test_split(x2, y, test_size=0.3, random_state=0)
    knn = neighbors.KNeighborsClassifier(n_neighbors=2)
    print("accuracy_score for ",a,knn.fit(x_train, y_train).score(x_test, y_test))
    y_pred = knn.predict(x_test)
    print("confusion_matrix for",a,"\n",confusion_matrix(y_test, y_pred))
    print()

accuracy_score for  Survived 0.6554307116104869
confusion_matrix for Survived 
 [[142  15]
 [ 77  33]]

accuracy_score for  Pclass 0.8614232209737828
confusion_matrix for Pclass 
 [[ 66   3   1]
 [  8  37   4]
 [  5  16 127]]

accuracy_score for  Sex 0.5917602996254682
confusion_matrix for Sex 
 [[70 28]
 [81 88]]

accuracy_score for  Age 0.06367041198501873
confusion_matrix for Age 
 [[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

accuracy_score for  SibSp 0.7265917602996255
confusion_matrix for SibSp 
 [[165  15   0   0   2   0   0]
 [ 40  22   3   0   0   0   0]
 [  5   2   1   0   0   0   0]
 [  2   2   1   2   0   0   0]
 [  0   0   1   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]

accuracy_score for  Parch 0.7902621722846442
confusion_matrix for Parch 
 [[192   5   1   0   0]
 [ 27  12   1   0   0]
 [ 15   5   7   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]

accurac

# When KNN Value is 3

In [25]:
for a in x1.columns:
    y = x1[a]
    x2 = x1.drop([a],axis=1)
    
    x_train, x_test, y_train, y_test = train_test_split(x2, y, test_size=0.3, random_state=0)
    knn = neighbors.KNeighborsClassifier(n_neighbors=3)
    print("accuracy_score for ",a,knn.fit(x_train, y_train).score(x_test, y_test))
    y_pred = knn.predict(x_test)
    print("confusion_matrix for",a,"\n",confusion_matrix(y_test, y_pred))
    print()

accuracy_score for  Survived 0.6891385767790262
confusion_matrix for Survived 
 [[122  35]
 [ 48  62]]

accuracy_score for  Pclass 0.8576779026217228
confusion_matrix for Pclass 
 [[ 62   6   2]
 [  8  28  13]
 [  3   6 139]]

accuracy_score for  Sex 0.6404494382022472
confusion_matrix for Sex 
 [[ 49  49]
 [ 47 122]]

accuracy_score for  Age 0.08239700374531835
confusion_matrix for Age 
 [[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

accuracy_score for  SibSp 0.7340823970037453
confusion_matrix for SibSp 
 [[157  22   1   0   2   0   0]
 [ 27  31   3   2   2   0   0]
 [  5   1   1   1   0   0   0]
 [  1   3   0   3   0   0   0]
 [  0   1   0   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]

accuracy_score for  Parch 0.7865168539325843
confusion_matrix for Parch 
 [[190   7   1   0   0]
 [ 26  13   1   0   0]
 [ 15   5   7   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]

acc

# When KNN Value is 4

In [26]:
for a in x1.columns:
    y = x1[a]
    x2 = x1.drop([a],axis=1)
    
    x_train, x_test, y_train, y_test = train_test_split(x2, y, test_size=0.3, random_state=0)
    knn = neighbors.KNeighborsClassifier(n_neighbors=4)
    print("accuracy_score for ",a,knn.fit(x_train, y_train).score(x_test, y_test))
    y_pred = knn.predict(x_test)
    print("confusion_matrix for",a,"\n",confusion_matrix(y_test, y_pred))
    print()

accuracy_score for  Survived 0.6591760299625468
confusion_matrix for Survived 
 [[133  24]
 [ 67  43]]

accuracy_score for  Pclass 0.8239700374531835
confusion_matrix for Pclass 
 [[ 60   7   3]
 [  8  31  10]
 [  5  14 129]]

accuracy_score for  Sex 0.6367041198501873
confusion_matrix for Sex 
 [[ 64  34]
 [ 63 106]]

accuracy_score for  Age 0.09737827715355805
confusion_matrix for Age 
 [[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

accuracy_score for  SibSp 0.7078651685393258
confusion_matrix for SibSp 
 [[163  16   1   0   2   0   0]
 [ 38  20   3   2   2   0   0]
 [  5   1   0   2   0   0   0]
 [  1   4   0   2   0   0   0]
 [  0   0   1   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]

accuracy_score for  Parch 0.7865168539325843
confusion_matrix for Parch 
 [[193   4   1   0   0]
 [ 29  11   0   0   0]
 [ 15   6   6   0   0]
 [  0   1   0   0   0]
 [  1   0   0   0   0]]

acc