In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
dataset = pd.read_csv("train.csv")

In [4]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
from sklearn import preprocessing

In [6]:
from sklearn.metrics import accuracy_score

In [7]:
from sklearn.metrics import confusion_matrix

In [8]:
from sklearn import svm

In [9]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
884          887         0       2   
885          888         1       1   
886          889         0       3   
887          890         1       1   
888          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
884                              Montvila, Rev. Juozas    male  27.0      0   
885                       Graham, Miss. Margaret Edith  female  19.0      0   
886           Johnston, Miss. Catherine Helen "Carrie"  female  45.0      1   
887                              Behr, Mr. Karl Howell    male  26.0      0   
888                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
884      0            211536  13.0000   NaN        S  
885      0            112053  30.0000   B42        S  
886      2        W./C. 6607  23.4500   NaN        S  
887      0            111369  30.0000  C148        C  
888      0            370376   7.7500   NaN        Q  

[889 rows x 12 columns]

In [10]:
le = preprocessing.LabelEncoder()

In [11]:
dataset["Sex"] = le.fit_transform(dataset["Sex"])

In [12]:
dataset["Embarked"] = le.fit_transform(dataset["Embarked"])

In [13]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
884          887         0       2   
885          888         1       1   
886          889         0       3   
887          890         1       1   
888          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1   
2                               Heikkinen, Miss. Laina    0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1   
4                             Allen, Mr. William Henry    1  35.0      0   
..                                                 ...  ...   ...    ...   
884                              Montvila, Rev. Juozas    1  27.0      0   
885                       Graham, Miss. Margaret Edith    0  19.0      0   
886           Johnston, Miss. Catherine Helen "Carrie"    0  45.0      1   
887                              Behr, Mr. Karl Howell    1  26.0      0   
888                                Dooley, Mr. Patrick    1  32.0      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN         2  
1        0          PC 17599  71.2833   C85         0  
2        0  STON/O2. 3101282   7.9250   NaN         2  
3        0            113803  53.1000  C123         2  
4        0            373450   8.0500   NaN         2  
..     ...               ...      ...   ...       ...  
884      0            211536  13.0000   NaN         2  
885      0            112053  30.0000   B42         2  
886      2        W./C. 6607  23.4500   NaN         2  
887      0            111369  30.0000  C148         0  
888      0            370376   7.7500   NaN         1  

[889 rows x 12 columns]

In [14]:
x1 = dataset.drop(["Name", "PassengerId", "Ticket", "Cabin"],axis=1)

In [15]:
x1

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
884         0       2    1  27.0      0      0  13.0000         2
885         1       1    0  19.0      0      0  30.0000         2
886         0       3    0  45.0      1      2  23.4500         2
887         1       1    1  26.0      0      0  30.0000         0
888         0       3    1  32.0      0      0   7.7500         1

[889 rows x 8 columns]

In [21]:
import numpy as np
x1["Age"] = x1["Age"].astype(int)
x1["Fare"] = x1["Fare"].astype(int)

In [22]:
for a in x1.columns:
    y = x1[a]
    x2 = x1.drop([a],axis=1)
    x_train, x_test, y_train, y_test = train_test_split(x2, y, test_size = 0.3, random_state = 0)
    clf = svm.SVC(gamma=0.01, C=100)
    print("",clf.fit(x_train, y_train))
    y_pred = clf.predict(x_test)
    print("\n accuracy_scorec for ",a,":",accuracy_score(y_test, y_pred, normalize=True))
    print("confusion matrix for",a,":\n",confusion_matrix(y_test, y_pred))

 SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

 accuracy_scorec for  Survived : 0.7415730337078652
confusion matrix for Survived :
 [[124  33]
 [ 36  74]]
 SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

 accuracy_scorec for  Pclass : 0.9063670411985019
confusion matrix for Pclass :
 [[ 63   5   2]
 [  4  36   9]
 [  0   5 143]]
 SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

 accuracy_scorec f